### ISSUE TITLE
Different colours in Safari and Chrome

### ISSUE THREAD

**Issue by julianheinrich** [syntagmatic/parallel-coordinates#100]
I'm getting different colours loading http://syntagmatic.github.io/parallel-coordinates/ on Safari (Version 7.1.5 (9537.85.14.17):
![screen shot 2015-04-30 at 10 22 20 am](https://cloud.githubusercontent.com/assets/7494632/7404201/0d529792-ef23-11e4-8e2d-f9c0fbe6badf.png)

and Chrome (Version 42.0.2311.90 (64-bit):
![screen shot 2015-04-30 at 10 24 43 am](https://cloud.githubusercontent.com/assets/7494632/7404208/22aa73f8-ef23-11e4-8d9e-0f6f225b1311.png)

both on OS X 10.9.5. The colours on safari seem wrong, can anybody confirm this?

**Comment by julianheinrich** [comment]
@syntagmatic @bbroeksema @mcwillso 
this looks like a severe issue to me, am I the only one seeing this behaviour? Or am I missing something?

**Comment by syntagmatic** [comment]
`darker` is a deprecated composite mode, it should be `darken` for the broadest compatibility now.

**Comment by julianheinrich** [comment]
Thanks @syntagmatic for the hint.
fixed in 0df3db1
