### ISSUE TITLE
console now displaying message about multi-brush

### ISSUE THREAD

**Issue by mg1075** [syntagmatic/parallel-coordinates#101]
Is it really necessary to have the console show a message about d3.multibrush, even if it is not going to be used? 

https://github.com/syntagmatic/parallel-coordinates/blob/d30801e386db33f8c54ab68af77344e82cc67e65/d3.parcoords.js#L1233-L1237

```
  if (typeof d3.svg.multibrush !== 'function') {
	  console.log("multibrush requires d3.svg.multibrush");
	  return;
  }
```

**Comment by julianheinrich** [comment]
Not really. I wanted to discuss how to include multibrush anyway. As
submodule, library, or just adding it to the code base?
