### ISSUE TITLE
adding or removing source data

### ISSUE THREAD

**Issue by mg1075** [syntagmatic/parallel-coordinates#102]
I am not finding any examples of the source data for the parallel coordinates chart being added to, removed, or refreshed with new data. Is there a best practice way to do this? Or is there any decent way to do this?

**Comment by syntagmatic** [comment]
`parcoords.data(new_data).render()` should work

**Comment by mg1075** [comment]
Confirmed. Thanks.

**Comment by jduckworth** [comment]
The added data doesn't seem to respect the current brush settings, though. When I add data via this method it is hidden in the background if there is a brush active on any of the axes.
