### ISSUE TITLE
Multibrush does not work under firefox

### ISSUE THREAD

**Issue by bbroeksema** [syntagmatic/parallel-coordinates#105]
Try loading:

http://syntagmatic.github.io/parallel-coordinates/examples/brushing.html

In firefox. I get: ReferenceError: d3_vendorSymbol is not defined.

Looking a bit more into it seems to suggest that the d3.svg.multibrush is not compatible with the latest d3 (3.5.5) version. Why it does work under chrome is a complete mystery to me.

**Comment by bbroeksema** [comment]
https://github.com/humanitiesplusdesign/d3.svg.multibrush/issues/2

**Comment by julianheinrich** [comment]
works on Safari as well, so not working in Firefox only so far...
@bbroeksema do you want to fix the issue for this library using your [fix](https://gist.github.com/bbroeksema/dde0615d9fbb5ef4ca58)?
I can confirm that it works on all three browsers for me.

**Comment by bbroeksema** [comment]
@julianheinrich Yeah, I think it's the best we can do, and I need this "fix" as we have users using firefox. Note, that it is not just a fix, but also an "upgrade" as the current version of d3.svg.multibrush seems to be based on an older version of d3.

Actually I'm still completely puzzled why the current version is working with d3 v3.5.5 in Chrome in the first place.

**Comment by bbroeksema** [comment]
This is "solved" with in d3.svg.multibrush: https://github.com/humanitiesplusdesign/d3.svg.multibrush/issues/2
