### ISSUE TITLE
Parcoords rendering issue

### ISSUE THREAD

**Issue by inem** [syntagmatic/parallel-coordinates#111]
I am using parallel coordinates together with slickgrid in one project and I discovered strange behavior using one dataset. For some reason line jumps to wrong axis and then back:
![proteome_cluster__mshr668_2015_protein_quantitation_summary__ffc_intensity_](https://cloud.githubusercontent.com/assets/9665/8052738/915fa684-0e8a-11e5-9b9d-da11f641df6e.png)
Here's static page demonstrating the issue:
http://parcoords-bug.getforge.io/custom
Interesting that original example works ok with same dataset:
http://parcoords-bug.getforge.io/orig

Do you have an idea what could cause this issue? In which part of parcoords code should I dive in to debug this?
Thanks.

**Comment by syntagmatic** [comment]
This is likely an issue with null values. As a temporary fix, try setting null values to `0` in your data, so that the line runs along the bottom.

**Comment by inem** [comment]
This is the first thing I checked. Nulls are already replaced to zeroes: 
![proteome_cluster__mshr668_2015_protein_quantitation_summary__ffc_intensity_](https://cloud.githubusercontent.com/assets/9665/8134202/92e76a64-112d-11e5-9a89-26827e03eab2.png)
So it should be something else.. :\

**Comment by UntotaufUrlaub** [comment]
i cant see the strange behavior and the links dont work. can u make the strange bahavior more clear (higlight the line or show a single line)
