### ISSUE TITLE
Multi 1D brushing does not work in Firefox

### ISSUE THREAD

**Issue by DevonSimpson** [syntagmatic/parallel-coordinates#114]
http://syntagmatic.github.io/parallel-coordinates/examples/brushing.html 

Select 2D or multi 1D and the brush elements do not work. Specifically in firefox, they do work in Chrome.

**Comment by syntagmatic** [comment]
Only seeing this as a problem for 1D-axes-multi. The dropdown itself triggers: `ReferenceError: d3_vendorSymbol is not defined`, which breaks all subsequent brushing.

Reloading the page and testing 2D strums, that seems to work fine.
