### ISSUE TITLE
Bower package

### ISSUE THREAD

**Issue by jduckworth** [syntagmatic/parallel-coordinates#117]
Any talk of making this a bower package? It might be nice to manage as part of other bower dependencies. I might be willing to help with this if needed...

**Comment by syntagmatic** [comment]
There may be backwards-incompatible changes coming up in the next minor version number, so let's wait at least till then. Maybe even better to wait for version 1.0, but there's no roadmap or schedule for that.

**Comment by mcwillso** [comment]
What is the status with registering with Bower? I second @jduckworth with being willing to help.

**Comment by syntagmatic** [comment]
Thanks for the help and contributions. I'm ambivalent about registering as a bower package, but I'll try to remove any roadblocks for anyone trying to push the library forward.

**Comment by mcwillso** [comment]
Bower package is now available under "d3.parcoords". Install with "bower install d3.parcoords"
