### ISSUE TITLE
Set an alpha scale to represent time

### ISSUE THREAD

**Issue by callicles** [syntagmatic/parallel-coordinates#118]
As far as I have checked I don't think that's possible.

In order to represent time without adding an axis, I would like to be able to set the transparency of each array of data depending on a timestamp on that data.

The more the data is old, the more the line that is represented by should be faded.

An ideal interface would be like the one used by `.color` which can take a function as a parameter to set the color according to the data. Having the same for `.alpha` would be perfect.

**Comment by julianheinrich** [comment]
Indeed, this doesn't seem to be possible at the moment, thanks for pointing it out.

**Comment by dehli** [comment]
Hi @callicles, this is actually possible using just the `color` function.

```javascript
var colorFunction = function(d) {
    var alpha = 1.0; // Should use d.timeStamp to determine proper alpha value
    return "rgba(255,0,0" + alpha + ")";
};
```

**Comment by dehli** [comment]
Closing the issue due to no feedback.
