### ISSUE TITLE
set the axes order

### ISSUE THREAD

**Issue by viko123** [syntagmatic/parallel-coordinates#119]
Hi,
Is it possible to set to set the axes order, according say an array. I've tried passing an array to the .reorder() function but all it says is that reorder is undefined.

Thanks,
V

**Comment by UntotaufUrlaub** [comment]
hi :)
if you search for methods you should have a look in the api description. (there are (i think) all available methods listed).
I think what you search for is the .dimensions() function which gets an array of axes names.
you need to use detectDimensions first.
For example: (with the axes: name, age, gender)

var parcoords= d3.parcoords()("#example")
    .data(data)
    .detectDimensions()
    .dimensions(["name","age"])
    .render()
    .brushmodeMode("1D-axes")
