### ISSUE TITLE
dots and brushing

### ISSUE THREAD

**Issue by UntotaufUrlaub** [syntagmatic/parallel-coordinates#121]
hi :)
i try to deal with missing values, so i added dots.
now when i brush something the dots disappear. Is there a possibility that i can have the dots according to the brushed data. Means: where the still remaining lines intersect with axes are dots.

thanks in advance 
greetings Jones :)

**Comment by Git-me-outta-here** [comment]
You added dots? Can you elaborate?

There are now two ways to handle missing values (https://github.com/syntagmatic/parallel-coordinates/pull/128).

**Comment by syntagmatic** [comment]
https://github.com/syntagmatic/parallel-coordinates#parcoords_axisDots
