### ISSUE TITLE
D3 Timer Error

### ISSUE THREAD

**Issue by sbryfcz** [syntagmatic/parallel-coordinates#122]
Has anyone else noticed a D3 error related to the timer?

It even shows up on the demo page: https://syntagmatic.github.io/parallel-coordinates/
If you brush the first exhibit a bunch, it will eventually throw an error: 
   ec.c is not a function

Unminified this is: 
   d3_timer_active.c is not a function (d3.js:2159)

It seems like parallel continues to work (in some circumstances), but d3 transistions seem to break....so for example the progressive loader example will no longer work until the page is refreshed.

Any thoughts? Help? Thanks!

**Comment by syntagmatic** [comment]
This looks like a bug with that demo rather than d3.timer. It's this line, `brush` is a deprecated method:

`d3.timer(pc1.brush);`

Thanks for reporting @sbryfcz!

**Comment by sbryfcz** [comment]
Cool. I'm not losing my mind :)

Any thoughts on a work around for the time being? I'll try to investigate as well.

**Comment by syntagmatic** [comment]
It's actually not brushing itself that's the problem-- when it was working you could click on an axis and it would programmatically animate a brush moving up and down. The `brush` method was a way to manually trigger a brush event. Brushes got reworked and I think that method was removed.

**Comment by sbryfcz** [comment]
Ah. I see. Thanks for the help. I'll just disable that functionality for now.
