### ISSUE TITLE
Updating the plot after updating the types

### ISSUE THREAD

**Issue by UntotaufUrlaub** [syntagmatic/parallel-coordinates#127]
How do i update the plot after an update of the types (at first everything was render and then the update is triggered, activated from the user) of the axes (using .types(types)) ?

i tried stuff like

    parcoords.detectDimensions()
                    .render()
                    .removeAxes()
                    .createAxes();

or with an updateAxes() call.
Some possibilities result in nothing and others in the error "Uncaught TypeError: yscale[p] is not a function".
Or do i have to redraw the completely thing?

**Comment by syntagmatic** [comment]
Can you post the full example?
