### ISSUE TITLE
Multiple vertical selections on brushing

### ISSUE THREAD

**Issue by Traksewt** [syntagmatic/parallel-coordinates#25]
Thanks for the great library. One enhancement I'd like is the ability for adding multiple regions for brushing on the same axis. Possibly by using a meta key (ALT/Command ?) to indicate to add to the brush selection instead of removing the existing one.

**Comment by julianheinrich** [comment]
This issue has only partly been fixed, as the current version does not respect any meta keys.
Also, multiple brushes are only available if d3.svg.multibrush is included prior to loading the library (see the brushing example).

@syntagmatic, @bbroeksema  Feel free to reopen this issue if you feel that my solution is not appropriate.
