### ISSUE TITLE
New example with a Map

### ISSUE THREAD

**Issue by thoralf-gutierrez** [syntagmatic/parallel-coordinates#259]
Hey guys!

We've built our own data exploration tool, with the help of your great library :-) Thanks a lot for the awesome work, I'm new to D3.js but it was pretty easy to get started with your examples!

Here's the result, where I link the parallel coordinates with a Map: https://realimpactanalytics.github.io/d4g-hackathon-malaria-viz/

The Map gets really useful when you filter on the dimensions, to quickly understand where those lines are located in the country. If you guys feel this could fit in the `In the Wild` examples linked on the homepage, I'm happy to propose a PR!

Cheers,
Thoralf

**Comment by syntagmatic** [comment]
Thanks Thoralf, this is a great example! I'll leave this issue open and add the link soon.
