### ISSUE TITLE
Special characters i tsv header?

### ISSUE THREAD

**Issue by TorbenOestergaard** [syntagmatic/parallel-coordinates#268]
This is probably a trivial question. Is it possible to include special characters in the header of the tsv (or csv) file? For example, it is sometimes useful to include units such as "°" and "m²"

PS: Still love this plot. Thanks for all your efforts..

**Comment by syntagmatic** [comment]
That should work just fine! Go ahead and reopen if it doesn't work.

**Comment by TorbenOestergaard** [comment]
Hmm.. Doesn't work for me? I use version 0.7 and the special characters get replaced by a black rectangle/diamond with a white question mark inside. Do I need to change the font type somehow? (The default looks like Arial)
![udklip](https://cloud.githubusercontent.com/assets/10668865/12669688/ca3b3398-c662-11e5-9cae-96cf6e7a782d.PNG)

**Comment by syntagmatic** [comment]
Try adding this tag near the top of the HTML file, if it's not there already:

```
<meta charset="utf-8">
```

**Comment by TorbenOestergaard** [comment]
I added the charset="utf" tag but apparently it didn't help. I have tried two of your examples: table.html (with tsv file and divgrid table) and slickgrid.html (with csv file). Tried both Chrome and Firefox (and emptied the cache and reloaded it). Any suggestions? Much appreciated..

**Comment by jfourment** [comment]
Hi, 
Same problem here, we want to include some special chars for currencies (like cent symbol) and it doesn't work whatever charset is defined. 
I also tried to include html entities in dimension labels but they are not decoded. either.

**Comment by syntagmatic** [comment]
<img width="126" alt="screen shot 2016-02-02 at 3 37 36 pm" src="https://cloud.githubusercontent.com/assets/156229/12768187/f0f37cd0-c9c2-11e5-8145-2e8975e2cb6e.png">

Hmm, I can't seem to reproduce the issue on either the table.html example or slickgrid csv upload. It works in both Chrome and Firefox.

Are you both on Windows? I wonder if it's an OS-related issue somehow.

**Comment by jfourment** [comment]
I'm on Ubuntu.

**Comment by TorbenOestergaard** [comment]
I'm on windows..

**Comment by syntagmatic** [comment]
This is the default style for the axis label font:

https://github.com/syntagmatic/parallel-coordinates/blob/master/d3.parcoords.css#L2

```
font: 14px sans-serif;
```

Can you try playing with other fonts to see if it works?

**Comment by mcwillso** [comment]
I was able to reproduce and got the upload example working by setting the FileReader encoding(http://stackoverflow.com/questions/12448595/get-set-file-encoding-with-javascripts-filereader) like:  reader.readAsText(file, 'ISO-8859-1');

**Comment by TorbenOestergaard** [comment]
@syntagmatic : Tried to change the font-family as you suggest. It changed the fonts accordingly, though still without the special characters.

@mcwillso : Great. Also works on my computer when running the "upload.html" example. This example uses a FileReader to read a csv file. Do you know a similar fix for the d3.tsv loader used in "table.html" among others?

**Comment by syntagmatic** [comment]
So this is caused by ISO-8859-1 encoded data files?

Papaparse uses the FileReader API internally and could accept the same encoding config:

http://papaparse.com/docs#config

**Comment by TorbenOestergaard** [comment]
Haven't thought of looking at the encoding of the csv/tsv files. Apparently, my files were decoded as "UTF-8 without BOM". Changed the encoding to "UTF-8" in Notepad++ and now everything seems to work :-) Thanks a lot for all your feedback!
