### ISSUE TITLE
How to make brushes stick to ticks

### ISSUE THREAD

**Issue by jfourment** [syntagmatic/parallel-coordinates#270]
Hi all,

Is there any way to make the brush to only use ticks and subticks as increments instead of pixels?
If I define axis with 0.1 ticks for example, I want to be able to only move the brush along these ticks. 
I don't want to be able to define a  range [0.12 - 0.63 ] for example.

Cheers

**Comment by syntagmatic** [comment]
This isn't a solution, which probably requires modifying the core library, but here's an example of snapping to a D3 scale:

http://bl.ocks.org/mbostock/6232537

**Comment by jfourment** [comment]
So it's called snapping ;-) I will look into that. Thanks!
