### ISSUE TITLE
"Jumping" one column

### ISSUE THREAD

**Issue by sergionegri** [syntagmatic/parallel-coordinates#272]
I've seen that there is the possibility to manage null values, basically placing them either on top or on bottom. It would be nice to have the possibility also to skip a column, so if there are 3 columns, A, B, C, we could link "C1" to "A1" without passing from any element in B.

The workaround of course is to create a dummy B element called "B not assigned", but it's inelegant (and it seems several Cs pass through the same dummy B when it's not true)

Thank you!

**Comment by julianheinrich** [comment]
There is a `hideAxis` function, but I guess you want to keep the axis visible?

**Comment by sergionegri** [comment]
Yep. It should be visible, especially because some data will skip it, others won't

**Comment by julianheinrich** [comment]
ok but then you would need to distinguish null values from those that actually sit at the axis and just pass through straight. So in theory, you could achieve what you want by adjusting the values for B depending on its neighbouring axes so that lines 'appear' to go straight from A to C, right?

**Comment by sergionegri** [comment]
Yeah, but rearranging the axis would make the appearance disappear. Plus it won't work with non numerical axis :(

**Comment by julianheinrich** [comment]
yes, it would be tedious to implement. Might be easier to do once #91 is fixed.

**Comment by sergionegri** [comment]
Probably. It would be nice, considering that there is a great deal of rework underway, if this feature could be taken into account. If not developed at least having the data structure in place so that it does not pose a constraint that would impede it

**Comment by syntagmatic** [comment]
@sergionegri Try filtering down to a few polylines in this example and see if it has the behavior you want:

http://bl.ocks.org/syntagmatic/0d1635533f6fb5ac4da3

If it does, some workarounds might be to work from that example instead of d3.parcoords.js, or hack d3.parcoords.js to use similar rendering code for each polyline.

**Comment by syntagmatic** [comment]
Screenshot of a polyline that skips columns:

<img width="923" alt="screen shot 2016-02-15 at 1 24 22 pm" src="https://cloud.githubusercontent.com/assets/156229/13060570/6ea232e2-d3e7-11e5-8a5b-aa60b3a633a8.png">

**Comment by sergionegri** [comment]
It might indeed work, thank you!
