### ISSUE TITLE
No Versions Available

### ISSUE THREAD

**Issue by dehli** [syntagmatic/parallel-coordinates#281]
Hi, I was messing around with your library using bower and I noticed it doesn't have any versions (even though I noticed you've been versioning the package.json file). I think this can be fixed by giving each release the appropriate tag (there's a SO question [here](http://stackoverflow.com/questions/26571739/bower-install-no-versions-available)).

I tried fixing this in a pull request, but then I realized tags can't be merged from forks. This is the script I wrote that would do the same. 

If you'd like to see how it would look on the main branch, you can see my fork [here](https://github.com/dehli/parallel-coordinates/releases) which resulted from executing the same commands.

I'd appreciate if you could look over where I tagged each version to ensure that it looks right to you before pushing them. Thanks!

    git tag 0.1.0 c6a5488200a36e613c426c9d1a802d2a8c6df75e
    git tag 0.1.1 9c170921d401d84e44cb5251d1aef9b71b9e49ee
    git tag 0.1.2 a9a7675e2eebe389ecacde4cfdb202899f2bd293
    git tag 0.1.3 05da7b5a0f17f1f9baa181d3360e7e9ae6063c73
    git tag 0.1.4 9e2b69f02bd7f7641c178e00ff656ca710583620
    git tag 0.1.5 baf13fed9030843f77815a40884f1facb792a782
    git tag 0.1.6 7b6477beefef257ca4867e5fafdfdc5caab94531
    git tag 0.1.7 0c1b1a8fce40fb1a52676d454cc98686c557d5ce
    git tag 0.2.0 226aca5179fc395645a56071722b30a24a40ab81
    git tag 0.2.1 7d3b2704a9ea2c748dae7fee3c2f2d21df474e14
    git tag 0.2.2 841e2d927ac78c066198a932bc3d6aba55347ebb
    git tag 0.3.0 eb566ed6471ee0a6c924bb89bdd33a3f6a410a4f
    git tag 0.3.1 98a689dff3a26111a1527be0a6e1c969a218920d
    git tag 0.3.2 de18e695d21c343488437691af0247808e650142
    git tag 0.4.0 bab6885c89a251a427c6310c76dd1d5d209f4e1a
    git tag 0.5.0 23adf91431932c0e14182be0d543cc26bf27fd98
    git tag 0.6.0 694dd3e7adb0058d84543c9a4cb902b4d2a35381
    git tag 0.7.0 ab3a6634d74dfa574936cc5cd0cd3ab2dbb6b21c

    git push --tags

**Comment by mcwillso** [comment]
Thanks @dehli! I just pushed the tags.  

Also, I accidentally registered your git fork instead of forking your project and registering my own. So when you get a chance you should unregister your bower package which I titled 'delhi-parcoords'. Sorry about that.

**Comment by dehli** [comment]
Of course and awesome! Thanks for this great library! No worries, I just unregistered it. :)
