### ISSUE TITLE
Uncaught Reference Error: $V is not defined

### ISSUE THREAD

**Issue by didimitrie** [syntagmatic/parallel-coordinates#284]
Hello. Sorry if this is the wrong place to post this.
When using parallel coordinates I'm trying to smooth out the curves, as per example. I nevertheless get the error in the title, with the following stack:
```
compute_centroids @ Parallel.js:61555
single_curve @ Parallel.js:61625
color_path @ Parallel.js:61643
path_foreground @ Parallel.js:61697
pc.render.default @ Parallel.js:61475
pc.render @ Parallel.js:61440
dod3 @ Parallel.js:59795
SPKSliderControl.init @ Parallel.js:61034
[...]
```
Am not sure if it's something in my code, or something in the library. Also afraid I am a complete n00b at d3, so apologies in advance for a possible idiotic question. 

Tried the same with a [the link to data table example](https://syntagmatic.github.io/parallel-coordinates/examples/table.html) and getting the same errors.

**Comment by mcwillso** [comment]
Appears you need to include sylvester.js like:
```<script src="lib/sylvester.js"></script>```

**Comment by didimitrie** [comment]
Cool! Thanks a bunch. Maybe a quick hint on the website/example for this would be good - unless it's something obvious that only a complete bloke like me could miss it :)

**Comment by mcwillso** [comment]
Yeah I never knew we needed that library for the smoothness. I updated our dependencies/docs to reflect dependency on sylvester.
