### ISSUE TITLE
Indentation Standard

### ISSUE THREAD

**Issue by dehli** [syntagmatic/parallel-coordinates#286]
I'm going to try to implement some features into the library, and was wondering what was the preferred coding standard for spacing. I see in some areas there are 2 spaces for indentation, others have 4, and others use tabs. 

I personally prefer spaces and that's what most of the source currently uses, but was wondering if there was an official opinion. I think it would be helpful to add it to the README (or maybe somewhere else).

Thanks!

**Comment by syntagmatic** [comment]
Spaces, not tabs. The reference style is Mike Bostock's code, which doesn't always conform to 2 or 4 space indents.

http://bl.ocks.org/mbostock

**Comment by dehli** [comment]
Thanks @syntagmatic! I will go ahead and close this issue then.
