### ISSUE TITLE
doc bug on dimensions API

### ISSUE THREAD

**Issue by Sigfried** [syntagmatic/parallel-coordinates#292]
I think dimensions are being refactored (?), but the documentation is currently confused as to whether it's an object or array; or, at least, I am.

https://github.com/syntagmatic/parallel-coordinates#parcoords_dimensions says:

    var dimensions = {
          {"name":
              {
                  orient: 'right',
                  type: 'string',
                  tickPadding: 0,
                  innerTickSize: 8,
                  type: "string"
              }
          },
          {"protein": {type:"number"}},
          {"calcium": {type:"number"}};

I think it should either be:

    var dimensions = {
          "name":
              {
                  orient: 'right',
                  type: 'string',
                  tickPadding: 0,
                  innerTickSize: 8,
                  type: "string"
              },
          "protein": {type:"number"},
          "calcium": {type:"number"}};

Or something like:

    var dimensions = [
          {"name":
              {
                  orient: 'right',
                  type: 'string',
                  tickPadding: 0,
                  innerTickSize: 8,
                  type: "string"
              }
          },
          {"protein": {type:"number"}},
          {"calcium": {type:"number"}];

**Comment by mcwillso** [comment]
It is an object. Should read:
```
var dimensions = {
      {"name":
          {
              orient: 'right',
              type: 'string',
              tickPadding: 0,
              innerTickSize: 8,
              type: "string"
          }
      },
      {"protein": {type:"number"}},
      {"calcium": {type:"number"}}
     };
```
Missing one last curly. I will update shortly.

**Comment by Sigfried** [comment]
I think it should be my first example above. I don't think what you have is valid javascript, right?

**Comment by dehli** [comment]
@Sigfried You're right. There's no key for the first object inside of dimensions.

**Comment by mcwillso** [comment]
Ah. Yeah. [https://syntagmatic.github.io/parallel-coordinates/examples/axis-config.html](url)
