### ISSUE TITLE
flipAxisAndUpdatePCP bug?

### ISSUE THREAD

**Issue by Sigfried** [syntagmatic/parallel-coordinates#294]
I think there is a bug here:

https://github.com/syntagmatic/parallel-coordinates/blob/master/src/axis.js#L8

    function flipAxisAndUpdatePCP(dimension) {
       var g = pc.svg.selectAll(".dimension");

       pc.flip(dimension);

       d3.select(this.parentElement)
          .transition()
            .duration(__.animationTime)
            .call(axis.scale(__.dimensions[dimension].yscale));

        pc.render();
     }

`this` is undefined in this function, at least for me it is.

**Comment by dehli** [comment]
How are you calling `flipAxis`?

**Comment by Sigfried** [comment]
pc.flipAxes(['month'])

**Comment by dehli** [comment]
Maybe it has to do with the ordering? In `basic.html` the following code works.

```
var parcoords = d3.parcoords()("#example")
    .data([
        [0,-0,0,0,0,1],
        [1,-1,1,2,1,1],
        [2,-2,4,4,0.5,1],
        [3,-3,9,6,0.33,1],
        [4,-4,16,8,0.25,1]
    ])
    .render()
    .createAxes()
    .flipAxes(['0']);
```

Are you calling it after `createAxes` has been called? If that's the case, I can make sure to update the documentation.

**Comment by Sigfried** [comment]
I am calling it after everything else. But I might be screwing something else up because brushing and reordering aren't working on my chart even though I'm turning those on.

**Comment by dehli** [comment]
Ahh, are you including `sylvester.js` and `d3.svg.multibrush.js`?

**Comment by Sigfried** [comment]
Ah, no. I'll go get those.

**Comment by Sigfried** [comment]
I'm not sure what https://github.com/Git-me-outta-here/react-parallel-coordinates is doing to get brushing to work in react that I wasn't doing (though it isn't including sylvester and multibrush), but I'm back to using it (with a couple fixes to use the latest version of parallel-coordinates). Still not able to flipAxes.

**Comment by Sigfried** [comment]
I see now that the code is actually working, the yscale domain is getting flipped, but visibly on the chart nothing is happening, it appears unflipped.

**Comment by Sigfried** [comment]
Nevermind. I just have to call .render().createAxes() after calling .flip().

**Comment by dehli** [comment]
Glad you got it working! :)

**Comment by Sigfried** [comment]
Thanks!
