### ISSUE TITLE
Rotating Labels

### ISSUE THREAD

**Issue by dehli** [syntagmatic/parallel-coordinates#299]
I discovered a strange ~~bug~~ *feature*... if you scroll while the mouse is over an axis label it will rotate all of the labels. I will investigate it.

![image](https://cloud.githubusercontent.com/assets/5856011/14536765/11d0f402-0242-11e6-889e-97ab9858d456.png)

**Comment by syntagmatic** [comment]
I'm not sure when it was added, but it's not a good feature to enable by default.

A convenience function for rotating the labels is fine, but the mouse interaction isn't necessary in a default plot.

**Comment by dehli** [comment]
I went through the commit history and saw that it was added here: https://github.com/syntagmatic/parallel-coordinates/commit/aa17162a7459279edb638f7ba3a71da9adb5830f

I'm going to make it disabled by default and only enable it if you specifically set it to be on.

**Comment by dehli** [comment]
Closed with #315
