### ISSUE TITLE
Include white space between highest/lowest data value and highest/lowest tick mark

### ISSUE THREAD

**Issue by tbadams45** [syntagmatic/parallel-coordinates#309]
Hi,

I have the following parcoords plot:
![china_js](https://cloud.githubusercontent.com/assets/8332396/16024889/322cd142-3192-11e6-9e77-8db4ad6c074c.PNG)

On the rightmost axis (barley), the max value is ~465. I'm trying to include a tick mark at 500 and have there be white space in between this tick mark and the max value, like the picture below.
![china_paper](https://cloud.githubusercontent.com/assets/8332396/16024882/23db5c12-3192-11e6-8925-685af6b8f6aa.PNG)

How should I do this? Setting the axis with
`parcoords.dimensions("Barley_1000_tons":
		{
			orient: 'left',
			title: 'Barley (kiltons)',
			innerTickSize: 5,
			outerTickSize: 8,
			type: "number",
			tickValues: [100,200,300,400,500]
		})`

 will include the tick mark at the correct location, but the label will be above the top of the parcoords plot (see pic below).
![china_js_inspect](https://cloud.githubusercontent.com/assets/8332396/16025037/0d82d930-3193-11e6-8a58-1de6dc4a16f2.PNG)

I'm attempting to do the same thing with a tick mark at 100, but the value is ~110.

**Comment by mcwillso** [comment]
You need to configure the scale attribute in the dimension config using a linear domain, this will determine the height of the axis relative to the data set. Something like this in your dimension config should work:
```
yscale: d3.log.linear.domain([100,500]),
```
Let me test a bit real quick.

**Comment by mcwillso** [comment]
I was close. Try this:
```
var range = parcoords.height() - parcoords.margin().top - parcoords.margin().bottom;

parcoords.dimensions("Barley_1000_tons": 
{ 
orient: 'left',
 title: 'Barley (kiltons)',
 innerTickSize: 5,
 outerTickSize: 8,
 type: "number",
 tickValues: [100,200,300,400,500],
 yscale: d3.scale.linear().domain([0, 500]).range([range, 1])
})
```

**Comment by tbadams45** [comment]
Perfect. Many thanks.
