### ISSUE TITLE
One to Many Mapping on Axis

### ISSUE THREAD

**Issue by mohithingorani** [syntagmatic/parallel-coordinates#314]
In my dataset there are a few one to many possible mappings.
For example Value A on Axis 1 is mapped to Value B, C,E on Axis 2.

What should i do in such a scenario?
Thanks!

**Comment by syntagmatic** [comment]
Duplicate of #304 
The only way to model it currently is to have an extra row of data each for B, C and E. Multiple attributes per axis are not supported.
