### ISSUE TITLE
Error while using edge bundling

### ISSUE THREAD

**Issue by Sanatramesh** [syntagmatic/parallel-coordinates#320]
Hi,

I tried to run the code for edge bundling and I could see the rendering first time. But, when I change the smoothness I get the following error:
d3.parcoords.js:527 Uncaught ReferenceError: $V is not defined
compute_centroids @ d3.parcoords.js:527
single_curve @ d3.parcoords.js:613
...

Can you please let me know how to resolve this issue.

Thanks

**Comment by timelyportfolio** [comment]
See if this might help https://github.com/syntagmatic/parallel-coordinates/issues/284.
