### ISSUE TITLE
D3 V4 Examples

### ISSUE THREAD

**Issue by syntagmatic** [syntagmatic/parallel-coordinates#337]
This project is too complex with too many outstanding issues for me to port to V4, but I have implemented some parallel coordinates examples with several of the features from this library and some enhancements to the core pattern described in https://github.com/syntagmatic/parallel-coordinates/issues/91

Here are the two examples:

Exoplanets II
https://bl.ocks.org/syntagmatic/482706e0638c67836d94b20f0cb37122

Nutrient Parallel Coordinates IV
https://bl.ocks.org/syntagmatic/05a5b0897a48890133beb59c815bd953

**Comment by syntagmatic** [comment]
Also check out this repo for a port by @mlarosa2 if you need features from the library in v4 https://github.com/mlarosa2/parcoords

**Comment by syntagmatic** [comment]
See #326 for past discussion

**Comment by BigFatDog** [comment]
I've ported parcoords to D3 V4 and ES6 to a project called [parcoords-es (https://github.com/BigFatDog/parcoords-es).
All original parcoords examples have been ported and verified.

In fact, it is totally OK to use parcoords with d3 v4 modules. However, I create parcoords-es because I do need a pure D3 V4 version of this visualization in my work.

Thank you for creating this visualization!

**Comment by mutantkeyboard** [comment]
@BigFatDog wow man. This is awesome. Just a quick question. Did you try using this with TS?

**Comment by BigFatDog** [comment]
No, I didn't. I haven't seriously considered TS in my visualizations yet.

**Comment by Abhijeet-Das** [comment]
Here is a simpler version of ordinal and numerical parallel coordinate in d3 V4.
Is there a way to brush ordinal axis as well ; like the "name " column in this example 
http://plnkr.co/edit/TiM6ZsvMTTBhh8ZdMoFQ?p=preview

**Comment by syntagmatic** [comment]
The examples

**Comment by Abhijeet-Das** [comment]
Hello , 

Can anyone please share a little simpler parallel coordinate example in d3 V4 , that has both ordinal and numerical axis. Also basic features like brushing , brush snapping and dragging .

Any help would be highly appreciated. 
Thanks

**Comment by magic-lantern** [comment]
@syntagmatic,

Is it possible to direct users to @BigFatDog or other projects that work with the current D3 (v4)? Perhaps a link in the main readme?

This project is great and works well - I just had many struggles until I found this issue and saw that people have already done a port.

**Comment by BigFatDog** [comment]
@syntagmatic 
I'm actively maintaining a d3v4 port of this project. Would you please consider adding my project [parcoords-es](https://github.com/BigFatDog/parcoords-es) to a D3V4 list in your readme?

Yun Xing

**Comment by Abhijeet-Das** [comment]
Hello, 
I was referring to  exoplanets example of parallel coordinate using d3 V4 https://bl.ocks.org/syntagmatic/482706e0638c67836d94b20f0cb37122

The issue I am observing is that when we brush the log scales (like Planet Semi major-axis or Planet orbital period) part of the graph appears to be broken in the middle.

Here is the screen shot of this .
https://user-images.githubusercontent.com/32777204/40357473-8ef90686-5dbc-11e8-8d64-cbaf3349cac0.png

Could anyone please tell me what is the correct interpretation of that !
Thanks

**Comment by Abhijeet-Das** [comment]
@syntagmatic , Thanks a lot for your quick response and clarification. I guess I should add some default values in my graph for the missing ones to make it appear consistent.  Thanks again

**Comment by syntagmatic** [comment]
I added a link to @BigFatDog's https://github.com/BigFatDog/parcoords-es in the readme and noted the library is no longer in active development in the Github project description.
