### ISSUE TITLE
Support for data items with undefined values

### ISSUE THREAD

**Issue by tmcw** [syntagmatic/parallel-coordinates#40]
I'm dealing with [a dataset](https://github.com/llimllib/bostonmarathon) that has blank values - like some data is `[a, b, c, d]` and other data is `[a, b, d]`. Is there a way to represent this in parallel-coordinates?

**Comment by UntotaufUrlaub** [comment]
i think what julianheinrich mentioned is a good solution :) 
the only thing im worried about is how the brushing on this specifiec place on the axis would look like.
greetings Jones :)
