### ISSUE TITLE
How to set scale tick values of each dimension?

### ISSUE THREAD

**Issue by mikequentel** [syntagmatic/parallel-coordinates#41]
This is a usage question, not a bug. If there is a more appropriate place for me to submit this, please let me know.

Given the following data, which represents results of demographic queries against a point located in a US Census block, I can graph the data as one parallel coordinate set, but it appears as a flat line with not tick values on the graph. This does not happen if I have multiple rows of results, which as I understand is because something autoscales the min/max values of ticks for each dimension. How can I manually set a range of min/max values for each axis? Many thanks for any advice on this.

Here is an example of what I want to plot, a set of key/values in an array (resultsArr):

 `[{"POPGRWCYFY":0.24,"AVGHHSZ10":2.64,"TOTPOP_CY":1237,"FEMALES_CY":691,"PFEMALE_CY":55.9,"MALES_CY":546,"PMALE_CY":44.1,"MEDAGE_CY":30.3}]`

The parallel coordinates then loads it like this:

```
var pc = d3.parcoords()("#paraCoordsDiv")
                    .data(resultsArr)
                    .alpha(0.4)
                    .render()
                    .ticks(20)
                    .createAxes();
```
For the one row (one object) plot, it appears like this screenshot:

![pc_single_feature](https://cloud.githubusercontent.com/assets/5436386/2973877/f62eef8a-db81-11e3-9bc2-02498de69ce4.jpg)

I'd like to have scale tick values similar to what gets presented when there is more than one object plotted, like this screenshot: 

![pc_multiple_features](https://cloud.githubusercontent.com/assets/5436386/2973890/1aad6c38-db82-11e3-8788-acda4f04d896.jpg)

Many thanks.

**Comment by jduckworth** [comment]
Thanks, this was useful to me as well.

**Comment by syntagmatic** [comment]
A couple examples here (straight D3, not using the library) of tick configuration in parallel coordinates.

http://bl.ocks.org/syntagmatic/4446b31c6cd746eedaeb
http://bl.ocks.org/syntagmatic/94be812f8b410ae29ee2
http://bl.ocks.org/syntagmatic/8ff691209324f1814257

That's not currently possible in d3.parcoords.js (or at least not easy or straightforward). For 0.8.0 I'd like to bring this pattern in. See #90. If you need custom ticks now, working from one of those three bl.ocks is a good route.

**Comment by mcwillso** [comment]
Tick values can be set like:
```
.dimensions(
{'power (hp)': {
                    title: "Power",
                    tickValues: [0,50,102]
                }
})
```
