### ISSUE TITLE
Fixed scale dimension

### ISSUE THREAD

**Issue by gianpo86** [syntagmatic/parallel-coordinates#51]
Hi, many compliments for the library :+1: 

maybe i´m wrong, but i´m not able to find a way to fix the dimensions manually; 

say that I have 3 axes (indeed 3 Dimensions) and I want that every of them has the min and max value from the bigger and the smaller of the 3: 
for instance
Dimension1) Min 10 max 100
Dimension2) Min -10 max 1000
Dimension3) Min -100 max 10
I would like that every axes has -100 and 1000 as extremes

there´s a way to do that?

many thanks

**Comment by UntotaufUrlaub** [comment]
very interesting topic!
(sadly i don't get it to work in my code)
can please someone add a working example?
