### ISSUE TITLE
Introducing a custom data type for axis.

### ISSUE THREAD

**Issue by shivam-agarwal** [syntagmatic/parallel-coordinates#65]
Hi,

I am new to the world of open source so kindly ignore if i'm writing this in wrong place.

I am working with parcoords.js and having a difficult time to make a custom data type. This is important as data will not always be of number, string or date type only. Eg - as rmastron mentioned in #45 , there was a difficulty adding scale for IP addresses.

Similarly there can be other data types which will be useful in analysis when displayed correctly via parallel coordinates. Can you kindly mention the correct way of doing so ?

**Comment by syntagmatic** [comment]
Here's an example of an IPv4 type: http://bl.ocks.org/syntagmatic/1ced118a51b49dadd4ea
