### ISSUE TITLE
No labels in an axis which has single value

### ISSUE THREAD

**Issue by Rijo13** [syntagmatic/parallel-coordinates#79]
There is no label in the axis if all rows in data have same value in that axis.

**Comment by syntagmatic** [comment]
Current behavior:

![screen shot 2015-01-19 at 1 31 41 am](https://cloud.githubusercontent.com/assets/156229/5798316/25433d36-9f7b-11e4-9a9b-e7b6c81f57bf.png)

Possible better behavior: Display the label of the single value. Place the value at the midpoint of the axis.

**Comment by syntagmatic** [comment]
https://github.com/syntagmatic/parallel-coordinates/commit/b41670cdadeca39e875111d4c77fae07c041a1c8

![screen shot 2015-02-16 at 5 39 35 am](https://cloud.githubusercontent.com/assets/156229/6212835/37f8442e-b59e-11e4-8262-f21fe42b78a4.png)

**Comment by Rijo13** [comment]
Still there is problem while brushing on single value axis. I sugest dont put the label to middle, but push it to top.
