### ISSUE TITLE
Type Error when data is added as array ( Uncaught TypeError: Cannot read property 'get' of undefined in d3.parcoords.js:386 ) 

### ISSUE THREAD

**Issue by lehle** [syntagmatic/parallel-coordinates#80]
Hey there, i am using the library to visualize features of geo-spatial trajectories and was running into the following problem: 
i am generating the parcoord from an array of data. Everything seems to work fine, except the bundling of the dimensions does not work. I get an error from: 

Uncaught TypeError: Cannot read property 'get' of undefined in d3.parcoords.js:386

my array is created using :
 mydata.push(){...}); 
everytime someone clicks a button to add a line of data i redraw the parallel coordinates. Everytime  more then 2 lines are added ( so my array includes 3 objects with the same dimensions ) the above mentioned error occurs and i can't figure out why. Smoothing and everything else works fine. Bundling gets an error as soon as i have 3 objects in the data array. 

Thanks in advance.

**Comment by syntagmatic** [comment]
lehle, I'm going to close this issue.

If you can post an example with the error for us to look at, feel free to reopen the issue.
