### ISSUE TITLE
Show labels only of brushed elements

### ISSUE THREAD

**Issue by fabricioflores** [syntagmatic/parallel-coordinates#81]
I'm working with > 1000 values and I need to see only brushed labels. I'm working in "on brushed" event but I don't know how to hide labels of unbrused values

**Comment by syntagmatic** [comment]
This doesn't happen automatically on the chart, but you could hook up a list view to the ```brush``` event to see the values. Right now there's no special logic on the axes about how they are displayed when brushes are applied.

**Comment by syntagmatic** [comment]
Protovis shows the max/min of the brush extent. You could attach text to the resize handles to do this.

https://mbostock.github.io/protovis/ex/cars.html

Here's an alternate workflow. It takes a few steps. In this [example](http://bl.ocks.org/syntagmatic/raw/3150059/) brush an axis. Then click the **Keep** button at the top left. The axes will all rescale to fit the brushed data, providing more space for labels on the brushed axis.

**Comment by fabricioflores** [comment]
Yes, I saw examples. The problem with Protovis' example is He used numbers, and I have strings... I was thinking to show labels only each 5 ticks. Is it possible with current implementation?

**Comment by fabricioflores** [comment]
@syntagmatic also, the brushing implementation that I was looking for is some like this: http://bl.ocks.org/syntagmatic/3150059

**Comment by bbroeksema** [comment]
Can you show a patch. I'm ingested in this as well and might add it to the library.

**Comment by fabricioflores** [comment]
Ok. Into function ```selected()``` before `if (actives.length === 0) return __.data;` is use this code:
```javascript
    var b = d3.selectAll('.dimension')[0]
      .forEach(function(element, i) {
        var dimension = d3.select(element).data()[0];
        if (actives.indexOf(dimension)!== -1) {
          var extent = extents[actives.indexOf(dimension)];
          d3.select(element)
            .selectAll('text')
            .style('font-weight', 'bold')
            .style('font-size', '13px')
            .style('display', function() {
              var value = yscale[dimension](d3.select(this).data());
              return extent[0] <= value && value <= extent[1] ? null : "none"
            });
        } else {
          d3.select(element)
            .selectAll('text')
            .style('font', '10px sans-serif')
            .style('font-weight', null)
            .style('display', null);
        }
        d3.select(element)
          .selectAll('.label')
          .style('display', null);
      });
      ;
```
