### ISSUE TITLE
Is it possible to somehow integrate Crossfilter with Parallel coordinates?

### ISSUE THREAD

**Issue by pablopareja** [syntagmatic/parallel-coordinates#85]
Hi, 

I was just wondering whether you know of any example of integration with http://square.github.io/crossfilter/ ?

Thanks!

**Comment by syntagmatic** [comment]
Sorry for not getting back on this.

It could very well make performance sense to use Crossfilter to perform the filtering. But we've found in developing the library that rendering is the primary bottleneck for most uses cases. Filtering data is several orders of magnitude faster, so it's preferable to leave that code simple and avoid dependencies for now.
