### ISSUE TITLE
Axis Metadata and Formatting

### ISSUE THREAD

**Issue by syntagmatic** [syntagmatic/parallel-coordinates#90]
Formatting the tick titles is one of the fundamental design tasks when adapting parallel coordinates to a dataset.

This library depends on D3 to automatically detect number, ordinal and date dimensions. There is no method for setting a custom tick format for a particular dimension.

The default `d3.svg.axis` function is hidden in the private `axis` variable. Axis methods like `ticks` and `tickValues` are rebound to `parcoords`, but that's almost useless when dimensions need different formatting. Changing that won't reapply it to axes already drawn and that configured applies to all dimensions.

The **`axis`** on each **`dimension`** should be exposed for reconfiguration along with a call to update modified SVG axes.

**Comment by bbroeksema** [comment]
And actually, I plan to work on a parallel-sets like axes for ordinal and nominal data. I have had several (internal) feature requests for being able to select two (or more) non-consecutive categories (e.g. in case of axes which represents clustering results). This is mostly an idea in my though at this point, but I hope to get to that in the next coming months.

**Comment by syntagmatic** [comment]
See #91

**Comment by syntagmatic** [comment]
See the configuration for `Mother's Age` as an example of how this could work.

http://bl.ocks.org/syntagmatic/8ff691209324f1814257

**Comment by mcwillso** [comment]
So I have a working solution for custom scales(https://github.com/syntagmatic/parallel-coordinates/issues/93) and tick formats (https://github.com/syntagmatic/parallel-coordinates/issues/41). Check out my example at http://mcwillso.github.io/parallel-coordinates/ pull request at https://github.com/mcwillso/parallel-coordinates/pull/1.  Is this a good enough solution or is there a better way of doing this?

**Comment by mcwillso** [comment]
Hmmmm, never mind I did not fully comprehend the depth of axis configuration and the potential level we should take this.

**Comment by mcwillso** [comment]
See http://syntagmatic.github.io/parallel-coordinates/examples/axis-config.html for examples on how to configure individual dimensions/axis.
