### ISSUE TITLE
Setting custom axis scales

### ISSUE THREAD

**Issue by nmulani** [syntagmatic/parallel-coordinates#93]
Hi - Thanks for all the very useful functionality in this reusable chart. I'm using the parallel coordinates chart with a dataset where all values are percentages, but none are exactly 1 or 100. Do you know a way I can set [1,100] as a custom domain for a some axes?

**Comment by bcohn12** [comment]
This would be very useful for me too, I hope there's a solution for this!

**Comment by syntagmatic** [comment]
This isn't supported now, unfortunately. Duplicates #90
