### ISSUE TITLE
Enhancement question... drag drop rearrange values in a dimension

### ISSUE THREAD

**Issue by sheshmantha** [syntagmatic/parallel-coordinates#94]
Hi,
I've been hitting my head against how do I enable the drag drop of a value within a dimension... I've hooked in the drag, dragstart, drag end events on "axis g" and am able to move the label for the value within a dimension (tick value) -- actually the transform of the selected g. But am at a loss on how to redraw the entire graph.

I see that something gets done with foreground and calling path() but I can't figure out what / why?  

Asked differently, if I've shuffled the domain values for a dimension, how do force a graph redraw??

Alternatively, how do i implement clicking on a tick label and turning that off in the display?

Any help is greatly appreciated.

Thanks,
s-

**Comment by syntagmatic** [comment]
These interactions aren't supported by the library. The goal here is to make something easy to get started with, but it's not well-designed for adding custom interactions outside of what's already available.

I would look into d3's axis, scale and drag behavior to implement them yourself. Here's a basic parallel coordinates to start from.

http://bl.ocks.org/mbostock/1341021
