### ISSUE TITLE
How works smoothness

### ISSUE THREAD

**Issue by Cracky5457** [syntagmatic/parallel-coordinates#97]
On this page

https://syntagmatic.github.io/parallel-coordinates/

pc0.smoothness(0.3).render(); works

But 

pc.smoothness(0.3).render(); doesn't on the basic sample

How use smoothness property ?

**Comment by julianheinrich** [comment]
Thanks @Cracky5457 for raising this issue.
Currently, smoothness depends on

1. loading sylvester.js and
2. setting a bundleDimension

So for the basic example, load sylvester.js and then:
   parcoords.bundleDimension(5).smoothness(0.3).render();

does the trick until these dependencies are fixed.

**Comment by benjaminlaird** [comment]
I would suggest adding comments at the top of `d3.paracoords.js` that sylvester.js is a requirement. It might be obvious to experienced users of this package, but for someone new, it took 45 min of debugging to figure out what the `$V` was in the `compute_centroids` function.

Making it very clear in the code when there are hard external dependencies would have made this a much easier bug to fix.
```
function compute_centroids(row) {
	var centroids = [];

	var p = __.dimensions;
	var cols = p.length;
	var a = 0.5;			// center between axes
	for (var i = 0; i < cols; ++i) {
		// centroids on 'real' axes
		var x = position(p[i]);
		var y = yscale[p[i]](row[p[i]]);
		centroids.push($V([x, y]));
```
