### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by mg1075** [syntagmatic/parallel-coordinates#98]
Is there an optimal way to make the parallel coordinates chart responsive?

**Comment by mg1075** [comment]
OK, so the documentation is not clear about it from my perspective, but the scatterplot example does show an approach for doing a resize.

https://github.com/syntagmatic/parallel-coordinates/blob/master/examples/scatterplot.html#L88-L90

```
window.onresize = function() {
    parcoords.width(document.body.clientWidth);
    parcoords.resize();
    ...
}
```

**Comment by mg1075** [comment]
One problem: brushing does not work after calling `resize`.

https://github.com/syntagmatic/parallel-coordinates/issues/76

**Comment by dpavlek** [comment]
`$(".container").width($(window).width());
    parcoords.width($(".container").width())
    parcoords.resize()
    .render();`

This is how I did it if anyone else comes across this issue.
