### ISSUE TITLE
selecting multiple lines to highlight

### ISSUE THREAD

**Issue by mg1075** [syntagmatic/parallel-coordinates#99]
Is there a canonical/recommended way to call `parcoords.highlight()` for more than one data item?

In the table example found here: https://github.com/syntagmatic/parallel-coordinates/blob/master/examples/table.html, one way to go about this is to have an outer array that you push data to when for an event such as clicking a row on the table grid; then you call `parcoords.highlight([myouterarray])` while passing the outer array to the highlight function. Seems do-able, just a little awkward, though.

**Comment by sergionegri** [comment]
+1

**Comment by mcwillso** [comment]
Passing an array to the highlight function is using the library as intended. 
```
parcoords.highlight(parcoords.data().splice(0,3));
```
Then to keep that same array up to date you could 
```
var newHighlightedArr = parcoords.highlighted().push(nextSelectedObj);
parcoords.highlight(newHighlightedArr);
```
